### ISSUE TITLE
アイコンに些細な問題

### ISSUE THREAD

**Issue by AlvarHHM** [akirattii/niichrome-2ch-browser#2]
ちょっど五月蝿いかもしれませんが、アイコンに些細な問題を発覚した
背景は真っ白の時は何の問題もないですが
妙な白線が接いでいる

![](http://i.imgur.com/ODmSO43.png)

**Comment by akirattii** [comment]
Hi @AlvarTheCoder, thanks for telling. 
I've noticed just now.
So I'll modifiy 128.png icon in today.
